In [1]:
import numpy
arr = numpy.array([1,2,3,4,5,])
print (arr)


[1 2 3 4 5]


In [4]:
import numpy as np
print(np.__version__)

1.19.2


In [5]:
import numpy
arr = numpy.array([1,2,3,4,5,])
print (arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# 0-D array

In [7]:
import numpy as np
arr = np.array(42)
print(arr)

42


# 1-D array

In [8]:
import numpy as np
arr = np.array([1,2,3,4,5])
print (arr)

[1 2 3 4 5]


# 2-D array

In [10]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


# 3-D array

In [11]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# 4-D array

In [13]:
import numpy as np
a= np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


# High dinmensional array

In [15]:
import numpy as np
arr = np.array([1,2,3], ndmin=5)
print(arr)

[[[[[1 2 3]]]]]


# ACCESS 2-D array 

In [16]:
import numpy as np
arr= np.array([1,2,3,4])
print (arr[0])

1


# ACCESS 3-D array

In [17]:
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


# negative indexing

In [18]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd array:',arr[1,-1])

last element from 2nd array: 10


# slicing

In [19]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]


# negative slicing

In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[-3:-1])

[4 5]


# step in slicing

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[1:5:2])

[2 4]


In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# 2-D slicing

In [26]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [27]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


# data types

In [35]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [31]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# defined data type

In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [33]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [36]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [37]:
import numpy as np
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# copy

In [38]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# view

In [39]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [40]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [41]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [42]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#  changing shape from 1-D to 2-D

In [43]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# CHANGING SHAPE FROM 1-D TO 3-D

In [44]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [46]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [47]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# CONVERTING MULTIDIMENSIONAL ARRAY TO I-D

In [48]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# ITERATING ARRAY GOING ONE BY ONE

In [49]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [51]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]
